### ISSUE TITLE
file missing for running main.py

### ISSUE THREAD

**Issue by bonniezyao** [PrincetonUniversity/BrainPipe#2]
Hi, I am running the program following the EXAMPLE.md page and there is an error in main.py line 10, where the xvfbwrapper does not exist in the repository. I am operating on a OSX but I doubt any platform differences is the cause.

Thanks for your help!
Bonnie

**Comment by austinhoag** [comment]
Hi Bonnie, 

Did you install the conda environment following the instructions here: https://github.com/PrincetonUniversity/BrainPipe/blob/master/INSTALLATION.md#python-setup

xvfbwrapper is a python package that should have been installed in your conda environment called `brainpipe`. That being said, I don't actually think xvfbwrapper is strictly necessary to run the example code so you may be able to comment that line out safely.

**Comment by bonniezyao** [comment]
Thank you for your reply! I did install the conda environment, but I had to delete some package versions in the yml file since it seems to be written for a Linux and I am running on a osx, as documented in https://stackoverflow.com/questions/48439159/failed-to-create-anaconda-environment-resolvepackagenotfound 
I will proceed running without the xvfbwrapper
